mvnbuild.version=28
mvnbuild.date=09/18/2022T10:09:38
mvnbuild.name=cloudwebfunnel
mvnbuild.host=MBP
mvnbuild.user=guentherhaslbeck
mvnbuild.osversion=OS name: "mac os x", version: "11.6.8", arch: "x86_64", family: "mac"
