# Define the root logger with appender file
log = ${catalina.base}/logs
#default tomcat log
log4j.rootLogger = INFO, FILE
#https://docs.oracle.com/cd/E29578_01/webhelp/cas_webcrawler/src/cwcg_config_log4j_file.html

# Define the file appender
log4j.appender.FILE=org.apache.log4j.DailyRollingFileAppender
log4j.appender.FILE.File=${log}/cloudwebfunnel.log

#log4j.appender.FILE=org.apache.log4j.rolling.RollingFileAppender
#log4j.appender.FILE.RollingPolicy=org.apache.log4j.rolling.TimeBasedRollingPolicy
#log4j.appender.FILE.RollingPolicy.FileNamePattern=${log}/application_%d{yyyy-MM-dd}.log

log4j.appender.FILE.Append=true
log4j.appender.FILE.encoding=UTF-8
log4j.appender.FILE.DatePattern='-'yyyy-MM-dd
log4j.appender.FILE.layout=org.apache.log4j.PatternLayout
log4j.appender.FILE.layout.ConversionPattern=%-d{yyyy-MM-dd HH:mm:ss} [%p] [%t] [%c] %m%n


# Define the layout for file appender
log4j.appender.FILE.layout=org.apache.log4j.PatternLayout
log4j.appender.FILE.layout.conversionPattern=%m%n

#application logger
log4j.logger.anything=DEBUG,anything


